protected/models/Product.php
<?php
class Product extends CActiveRecord{
	/*untuk menampung format harga produk 
	 *yg akan dikonvert ke bentuk mata uang*/
	public $price_product;
	
	public static function model($className=__CLASS__){
		return parent::model($className);
	}

	/*kembalikan ke tabel product 
	 *(maksudnya model ini akan menggunakan tabel product)*/
	public function tableName(){
		return 'product';
	}
	/*ini digunakan untuk memformat mata uang produk
	 *yang akan ditampilkan*/
	protected function afterFind(){
		parent::afterFind();
		$this->price_product=number_format($this->price,0,',','.');
		return TRUE;       
	}
	
	/*ini digunakan untuk mreplace tanda titik(.) yang ada di mata uang
	 *seperti (100.000) menjadi (100000)*/
	protected function beforeSave(){
		parent::afterFind();
		$this->price = str_replace('.','',$this->price);
		return TRUE;       
	}

	/*ini digunakan untuk rules dari masing-masing field 
	 *yang ada pada tabel product*/
	public function rules(){
		return array(
			array('product_name, category_id, price,description', 'required'),
			array('image', 'file', 'types'=>'jpg, gif, png','allowEmpty'=>true),
			array('category_id, price', 'numerical', 'integerOnly'=>true),
			array('product_name,image', 'length', 'max'=>555),
			array('id, product_name, category_id, price,image', 'safe', 'on'=>'search'),
		);
	}

	/*relasi tabel*/
	public function relations(){
		return array(
			/*merelasikan ketabel category*/
			'category'=>array(self::BELONGS_TO,'category','category_id')
		);
	}

	/*set attributes*/
	public function attributeLabels(){
		return array(
			'id' => 'ID',
			'product_name' => 'Product Name',
			'category_id' => 'Category',
			'price' => 'Price',
			'image' => 'Image',
		);
	}

	/*untuk search*/
	public function search(){
		$criteria=new CDbCriteria;
		$criteria->compare('id',$this->id);
		$criteria->compare('product_name',$this->product_name,true);
		$criteria->compare('category_id',$this->category_id);
		$criteria->compare('price',$this->price);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}
}
?>

protected/controllers/ProductController.php
<?php
class ProductController extends YiishopController {

	public $layout = "admin_page";
	/*set folder untuk uploads
	 *(silahkan pastikan bahwa 
	 *anda telah membuat folder images/products pada yiishop/)*/
	const URLUPLOAD = '/../images/products/';
	
	/*untuk detail product*/
	public function actionReview($id) {
		IsAuth::Admin();
		$this -> render('review', 
				array('model' => $this -> loadModel($id), 
			)
		);
	}
	
	/*untuk create product*/
	public function actionCreate() {
		IsAuth::Admin();
		/*panggil model product*/
		$model = new Product;
		/*jika data dikirim*/
		if (isset($_POST['Product'])) {
			/*cek file / gambar produk*/	
			$cekfile = $model -> image = CUploadedFile::getInstance($model, 'image');
			/*set attributes product*/
			$model -> attributes = $_POST['Product'];
			/*ambil value / nama gambar*/
			$model -> image = CUploadedFile::getInstance($model, 'image');
			/*jika data product disimpan*/
			if ($model -> save()) {
				/*jika file ada*/
				if (!empty($cekfile)) {
					/*set value field image dengan nama gambar
					 *dan upload gambar ke folder images/products*/
					$model -> image -> saveAs(Yii::app() -> basePath . self::URLUPLOAD . $model -> image . '');
					/*copy file yang barusan diupload ke images/products ke images/products/thumbs*/
					copy(Yii::app() -> basePath . self::URLUPLOAD . $model -> image, Yii::app() -> basePath . self::URLUPLOAD . 'thumbs/' . $model -> image);
					/*ambil filenya*/
					$name = getcwd() . '/images/products/thumbs/' . $model -> image;
					/*panggil component image dengan param $image*/
					$image = Yii::app() -> image -> load($name);
					/*resize gambar/thumb gambar*/
					$image -> resize(93, 0);
					/*simpan thumb image kembali gambar ke 
					 *images/products/thumbs*/
					$image -> save();
				}
				/*direct ke halaman product/review*/
				$this->redirect(array('review','id'=>$model->id));
			}
		}
		/*tampilkan form create produk*/
		$this -> render('create', 
				array('model' => $model, 
			)
		);
	}
	
	/*untuk update produk*/
	public function actionUpdate($id) {
		IsAuth::Admin();
		/*find produk by pk*/
		$model = $this -> loadModel($id);
		/*ambil gambar*/
		$image = $model -> image;
		/*jika data perubahan dikirim*/
		if (isset($_POST['Product'])) {
			/*cek file / gambar produk*/
			$cekfile = $model -> image = CUploadedFile::getInstance($model, 'image');
			/*jika file tidak ada*/
			if (empty($cekfile)) {
				/*set value attribute*/	
				$model -> attributes = $_POST['Product'];
				/*set image dari yang sudah ada*/
				$model -> image = $image;
				/*simpan perubahan data*/
				if ($model -> save()) {
					/*direct ke product/view*/
					$this -> redirect(array('review', 'id' => $model -> id));
				}
			} else {/*jika file ada*/
				/*set value attribute*/
				$model -> attributes = $_POST['Product'];
				/*ambil value / nama gambar*/
				$model -> image = CUploadedFile::getInstance($model, 'image');
				/*simpan perubahan data produk*/
				if ($model -> save()) {
					/*set value field image dengan nama gambar
					 *dan upload gambar ke folder images/products*/
					$model -> image -> saveAs(Yii::app() -> basePath . '/../images/products/' . $model -> image . '');
					/*copy file yang barusan diupload ke images/products ke images/products/thumbs*/
					copy(Yii::app() -> basePath . self::URLUPLOAD . $model -> image, Yii::app() -> basePath . self::URLUPLOAD . 'thumbs/' . $model -> image);
					/*ambil filenya*/
					$name = getcwd() . '/images/products/thumbs/' . $model -> image;
					/*panggil component image dengan param $image*/
					$image = Yii::app() -> image -> load($name);
					/*resize gambar/thumb gambar*/
					$image -> resize(93, 0);
					/*simpan thumb image kembali gambar ke 
					 *images/products/thumbs*/
					$image -> save();
					/*direct ke product/view*/
					$this -> redirect(array('review', 'id' => $model -> id));
				}
			}
		}
		/*render form update product*/
		$this -> render('update', 
				array('model' => $model, 
			)
		);
	}

	/*untuk delete produk*/
	public function actionDelete($id) {
		IsAuth::Admin();
		if (Yii::app() -> request -> isPostRequest) {
			// delete produk
			$this -> loadModel($id) -> delete();
			// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
			if (!isset($_GET['ajax']))
				$this -> redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
		} else
			throw new CHttpException(400, 'Invalid request. Please do not repeat this request again.');
	}

	

	/**
	 * Manages all models.
	 */
	public function actionAdmin() {
		
		IsAuth::Admin();
		
		$model = new Product('search');
		$model -> unsetAttributes();
		 

		if (isset($_GET['Product'])) {
			$model -> attributes = $_GET['Product'];
		}
		$this -> render('admin', array('model' => $model, ));

	}

	public function loadModel($id) {
		$model = Product::model() -> findByPk($id);
		if ($model === null)
			throw new CHttpException(404, 'The requested page does not exist.');
		return $model;
	}

	protected function performAjaxValidation($model) {
		if (isset($_POST['ajax']) && $_POST['ajax'] === 'product-form') {
			echo CActiveForm::validate($model);
			Yii::app() -> end();
		}
	}
	
	public function actionIndex() {
		/*gunakan layout store*/
		$this -> layout = 'store';
		/*order by id desc*/
		$criteria = new CDbCriteria( array('order' => 'id DESC', ));
		/*count data product*/
		$count = Product::model() -> count($criteria);
		/*panggil class paging*/
		$pages = new CPagination($count);
		/*elements per page*/
		$pages -> pageSize = 8;
		/*terapkan limit page*/
		$pages -> applyLimit($criteria);

		/*select data product
		 *cache(1000) digunakan untuk men cache data,
		 * 1000 = 10menit*/
		$models = Product::model() -> cache(1000) -> findAll($criteria);

		/*render ke file index yang ada di views/product
		 *dengan membawa data pada $models dan
		 *data pada $pages
		 **/
		$this -> render('index', array('models' => $models, 'pages' => $pages, ));
	}

	/*untuk search prouk*/
	public function actionSearch() {
		/*gunakan layout store*/
		$this -> layout = 'store';
		if (isset($_POST['Search'])) {
			$keyword = $_POST['Search']['keyword'];
			$category = $_POST['Search']['category'];
			//$this->redirect(array('product/search','c'=>$category,'key'=>$key));

			//$criteria = new CDbCriteria( array('order' => 'id DESC', ));
			if ($category == 'all-categories' && empty($keyword)) {
				$this -> redirect(array('product/'));
			}
			if ($category != 'all-categories' && empty($keyword)) {
				$criteria = new CDbCriteria( array('order' => 'id DESC', 'condition' => 'category_id=' . $category . ''));
			}
			if ($category == 'all-categories' && !empty($keyword)) {
				$criteria = new CDbCriteria( array('order' => 'id DESC', 'condition' => 'product_name like"%' . trim($keyword) . '%"', ));
			}
			if ($category != 'all-categories' && !empty($keyword)) {
				$criteria = new CDbCriteria( array('order' => 'id DESC', 'condition' => 'category_id=' . $category . ' AND product_name like"%' . trim($keyword) . '%"', ));
			}

			/*count data product*/
			$count = Product::model() -> count($criteria);
			/*panggil class paging*/
			$pages = new CPagination($count);
			/*elements per page*/
			$pages -> pageSize = 8;
			/*terapkan limit page*/
			$pages -> applyLimit($criteria);

			/*select data product
			 *cache(1000) digunakan untuk men cache data,
			 * 1000 = 10menit*/
			$models = Product::model() -> cache(1000) -> findAll($criteria);

			/*render ke file index yang ada di views/product
			 *dengan membawa data pada $models dan
			 *data pada $pages
			 **/
			$this -> render('index', array('models' => $models, 'pages' => $pages, ));
		} else {
			$this -> redirect(array('product/'));
		}
	}

	public function actionView($id) {
		/*gunakan layout store*/
		$this -> layout = 'store';

		/*select data berdasarkan primaryKey.
		 *cache(1000) untuk men cache data, 1000 = 10 menit
		 **/
		$model = Product::model() -> cache(1000) -> findByPk($id);
		/*jika data tidak ada akan dilempar ke 404*/
		if($model===null){
			throw new CHttpException(404,'The requested page does not exist.');
		}
		/*render ke file view.php dengan membawa
		 *data yang ditampung $model*/
		$this -> render('view', array('data' => $model));
	}
	
	
	/*untuk menambahkan product ke keranjang belanja*/
	public function actionAddtocart($id) {
		/*gunakan layout store*/
		$this -> layout = 'store';
		/*panggil model Cart*/
		$model = new Cart;
		/*set data ke masing masing field*/
		/*product_id*/
		$_POST['Cart']['product_id'] = $id;
		/*qty*/
		$_POST['Cart']['qty'] = 1;
		/*cart_code*/
		$_POST['Cart']['cart_code'] = Yii::app()->session['cart_code'];
		/*set ke attribut2*/
		$model -> attributes = $_POST['Cart'];
		
		/*update qty-nya jika produk sudah ada di dalam keranjang belanja
		 *menjadi +1*/
		if ($this -> addQuantity($id, Yii::app()->session['cart_code'], 1)) {
			/*direct ke halaman cart*/	
			$this -> redirect(array('cart/'));
		/*add ke keranjang belanja jika produk belum ada di keranjang*/	
		} elseif ($model -> save()) {
			/*direct ke halaman cart*/ 
			$this -> redirect(array('cart/'));
		} else {
			/*produk tidak ada di dalam data product kasih error 404*/
			throw new CHttpException(404, 'The requested id invalid.');
		}

	}
	
	/*function untuk update QTY produk di keranjang belanja*/
	private function addQuantity($product_id, $cart_code = '', $qty = '') {
		/*model Cart findBy attributes product_id dan cart_code*/
		$modelCart = Cart::model() -> findByAttributes(array('product_id' => $product_id, 'cart_code' => $cart_code));
		/*jika ada didalam keranjang belanja*/
		if (count($modelCart) > 0) {
			/*maka update qty nya*/
			$modelCart -> qty += $qty;
			/*simpan dan return true*/
			$modelCart -> save();
			return TRUE;
		} else {
			/*lain dari itu return false*/
			return FALSE;
		}
	}

	public function actionCategory($id) {
		/*gunakan layout store*/

protected/views/product/_form.php
<div class="form">
<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'product-form',
	'htmlOptions' => array('enctype' => 'multipart/form-data'),
	'enableAjaxValidation'=>false,
)); ?>

	<p class="note">Fields with <span class="required">*</span> are required.</p>

	<?php echo $form->errorSummary($model); ?>

	<div class="row">
		<?php echo $form->labelEx($model,'product_name'); ?>
		<?php echo $form->textField($model,'product_name',array('size'=>60,'maxlength'=>555)); ?>
		<?php echo $form->error($model,'product_name'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'category_id'); ?>
		<?php 
		echo $form->dropDownList($model,'category_id', CHtml::listData(Category::model()->findAll(), 'id', 'category_name'), array('empty'=>'--please select--'));
		?>
		
		<?php echo $form->error($model,'category_id'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'price'); ?>
		<?php echo $form->textField($model,'price'); ?>
		<?php echo $form->error($model,'price'); ?>
	</div>
	
	<?php if(!empty($model->image)){?>
	 
	<div class="row">		
		<?php echo CHtml::image(Yii::app()->request->baseUrl.'/images/products/'.$model->image.'','image',array("style"=>"width:93px;" ));?>
	</div>
	<?php }?>
	
	<div class="row">	
	<?php echo $form->labelEx($model, 'image');?>
	<?php echo $form->fileField($model, 'image',array('size'=>60,'maxlength'=>555));?>
	<?php echo $form->error($model, 'image');?>
	</div>
	
	<div class="row">
	<?php echo $form->labelEx($model, 'description');?>
	<?php echo $form->textArea($model, 'description',array('cols'=>50,'rows'=>5,'maxlength'=>555));?>
	<?php echo $form->error($model, 'description');?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton($model->isNewRecord ? 'Create' : 'Save'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- form -->

protected/views/product/admin.php
<h3>Data Products</h3>
<div>
	<?php echo CHtml::link('Add Product',array('product/create'));?>
</div>
<style type="text/css">
	.last{
		display: inline !important;
	}
	.first{
		display: inline !important;
	}
</style>
<?php $this->widget('zii.widgets.grid.CGridView', array(
	'id'=>'product-grid',
	'dataProvider'=>$model->search(),
	'filter'=>$model,
	'summaryText'=>'',
	'pager'=>array(
        'header'=> '',
        'firstPageLabel'=>'| <',
        'lastPageLabel'=>'> |',
        'nextPageLabel'=>'>',
        'prevPageLabel'=>'<',
    ),
	'columns'=>array(
		'id',
		'product_name',
		array('name'=>'category_id', 
		      'type'=>'html', 
			  'value'=>'$data->category->category_name','sortable'=>TRUE,
			  'filter' => CHtml::listData(Category::model()->findAll(),'id','category_name'),),
		array('name'=>'price',
			  'type'=>'html',
			  'value'=>'$data->price_product','sortable'=>TRUE,
		),
		array(
			'class'=>'CButtonColumn',
			'template'=>'{update}&nbsp;&nbsp;{delete}'
		),
	),
)); ?>

protected/views/product/category.php
<?php
/*untuk membuat breadcrumbs*/
$this -> breadcrumbs = array('Products' => array('product/'), 'Category', );
?>
<?php
$i=1;
foreach($models as $data):
	 if($i%2==0){$class="rightbox";}else{$class="leftbox";}
?>					 
<div style="height:170px; text-align:justify; padding-right: 3px ;margin-left:5px;margin-bottom:5px;border:1px solid #CCC;" class="<?php echo $class;?>">
	<div style="height: 130px;">
		<h3 style="float: left; margin-right: 15px; padding-right:12px; "><?php echo $data -> product_name;?></h3>
		<?php 
			/*untuk menampilkan gambar*/
			echo CHtml::image(Yii::app() -> request -> baseUrl . '/images/products/thumbs/' . $data -> image . '', '', array("style" => "margin-left:0px;padding:10px;clear:left;", "class" => "left", ));
		?>
		<br><br>
		<p>
			<b>Price:</b>
			<b>IDR <?php echo $data -> price_product;?></b>  
			<p style="margin-left: 15px;">
				<?php echo substr($data -> description, 0, 100);?>
			</p>		
			<div class="clear"></div>
			<br>
		</p>
	</div>
	<p class="readmore" style="float: right; position:; margin-right:11px; margin-bottom: 5px; margin-top: 0px;">
	<?php
		/*untuk membuat link update
		 *untuk admin yang login*/
		if (!Yii::app() -> user -> isGuest && !isset(Yii::app()->user->customerLogin)) {
			echo CHtml::link(
				CHtml::encode("Update"), 
				array(
				  'update', 
				  'id' => $data -> id)
				);
		}
	?>
	&nbsp;&nbsp;
	<?php 
		/*untuk link add to cart/beli*/
		echo CHtml::link(
			CHtml::encode("Beli"), 
			array(
		      'addtocart', 
			  'id' => $data -> id,
			  'p'=>$data->product_name)
	);?>
	&nbsp;&nbsp;
	<?php 
		/*untuk link detail produk*/
		echo CHtml::link(
			CHtml::encode("Detail"), 
			array('view', 
			  'id' => $data -> id,
			  'p'=>$data->product_name)
	);?>
	</p>
</div>	
<?php $i++;endforeach;?>

<!--untuk paging-->
<div style="float: right; margin-top: 5px; margin-bottom: 7px; margin-right: 18px;clear: both;">
<?php $this->widget('CLinkPager', array(
   'pages' => $pages,
   'header'=> '',
   'firstPageLabel'=>'| <',
   'lastPageLabel'=>'> |',
   'nextPageLabel'=>'>',
   'prevPageLabel'=>'<',
   'maxButtonCount'=>5,
))?></div>

protected/views/product/create.php
<h3>Create Product</h3>

<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/product/index.php
<?php
/*digunakan untuk membuat breadcrumbs*/
$this -> breadcrumbs = array('Products', );
?>
<?php
$i=1;
/*foreach data product yang di bawa $models*/
foreach($models as $data):
	/*membuat nama class css rightbox/leftbox
	 *jika hasil mod 2 dari i 0 maka $class = rightbox
	 *selain itu $class = leftbox*/
	 if($i%2==0){$class="rightbox";}else{$class="leftbox";}
?>
<div style="height:170px; text-align:justify; padding-right: 3px ;margin-left:5px;margin-bottom:5px;border:1px solid #CCC;" class="<?php echo $class; //tempilkan class css?>">
	<div style="height: 130px;">
		<h3 style="float: left; margin-right: 15px; padding-right:12px; ">
			<?php echo $data -> product_name; ?>
		</h3><!--width:93px;clear:left;-->
		<?php 
			/*untuk menampilkan gambar*/
			echo CHtml::image(Yii::app() -> request -> baseUrl . '/images/products/thumbs/' . $data -> image . '', '', array("style" => "margin-left:0px;padding:10px;clear:left;", "class" => "left", )); 
		?>
		<br><br>
		<p>
			<b>Price:</b> 
			<b>IDR <?php echo $data -> price_product; ?></b>  
			<p style="margin-left: 15px;"><?php echo substr($data -> description, 0, 100); ?></p>
			<div class="clear"></div>
			<div style="position:; margin-top: 50px;">
				&nbsp;
			</div>
			<br>   
	</div>
	<p class="readmore" style="float: right; position:; margin-right:11px; margin-bottom: 5px; margin-top: 0px;">
		<?php
		/*untuk membuat link update jika user login is admin*/
		if (!Yii::app() -> user -> isGuest && !isset(Yii::app()->user->customerLogin)) {
			echo CHtml::link(CHtml::encode("Update"), array('update', 'id' => $data -> id));
		}
		?>
		<!--membuat link add to cart-->
		&nbsp;&nbsp;
		<?php echo CHtml::link(CHtml::encode("Beli"), array('addtocart', 'id' => $data -> id, 'p'=>$data->product_name)); ?>
		<!--membuat link detail product-->
		&nbsp;&nbsp;
		<?php echo CHtml::link(CHtml::encode("Detail"), array('view', 'id' => $data -> id, 'p'=>$data->product_name)); ?>
	</p>
</div>

<?php $i++; endforeach;?>
<!--untuk paging-->
<div style="float: right; margin-top: 5px; margin-bottom: 7px; margin-right: 18px;clear: both;">
<?php $this->widget('CLinkPager', array(
   'pages' => $pages,
   //'cssFile'=>Yii::app()->request->baseUrl.'/css/pager2.css',
   'header'=> '',
   'firstPageLabel'=>'| <',
   'lastPageLabel'=>'> |',
   'nextPageLabel'=>'>',
   'prevPageLabel'=>'<',
   'maxButtonCount'=>5,
))?></div>

protected/views/product/review.php
<h3>View Product #<?php echo $model->id; ?></h3>

<?php $this->widget('zii.widgets.CDetailView', array(
	'data'=>$model,
	'attributes'=>array(
		'id',
		'product_name',
		'category_id',
		'price',
	),
)); ?>

protected/views/product/update.php
<h3>Update Product <?php echo $model->product_name; ?></h3>

<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>
 

protected/views/product/view.php
<?php
/*untuk membuat breadcrumbs*/
$this -> breadcrumbs = array('Products' => array('index'), $data -> product_name, );
?>

<div style="padding-right: 10px ;margin-left:5px;margin-bottom:15px;border:1px solid #CCC; margin-right: 5px; margin-top: 5px; text-align: justify; padding-top: 15px;">
	<a href="<?php echo Yii::app() -> request -> baseUrl . '/images/products/' . $data -> image;?>">
		<?php 
			/*menampilkan gambar*/
			echo CHtml::image(Yii::app() -> request -> baseUrl . '/images/products/' . $data -> image . '', '', array("style" => "width:200px;margin-left:10px;", "class" => "left", 'hspace' => 12));
		?>
	</a>
	<h3 style="float: left;">
		<?php echo $data -> product_name;?>
	</h3>
	<br><br>
	<p>
		<b>Price:</b> 
		<b>IDR <?php echo $data -> price;?></b>
		<p><?php echo $data -> description;?></p>
		<p class="readmore" style="float: right; margin-right:11px; height:15px; width:100px; background:#dcebf1; text-align:center;  margin-top: 110px;  ">
			<b>
				<?php
				/*membuat link update bagi admin yang login
				 *dan mengakses store*/
				if (!Yii::app() -> user -> isGuest && !isset(Yii::app()->user->customerLogin)) {
					echo CHtml::link(CHtml::encode("Update"), array('update', 'id' => $data -> id));
				}
				?>
			</b>
			&nbsp;&nbsp;		
			<b>
				<!--link beli/add to cart-->
				<?php echo CHtml::link(CHtml::encode("BELI"), array('addtocart', 'id' => $data -> id, 'p'=>$data->product_name));?>
			</b>
			&nbsp;&nbsp;
		</p>
		<div class="clear"></div>
		<br>
	</p>   
</div>