protected/controllers/AccountController.php
<?php
class AccountController extends Controller {
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout = 'store';

	/**
	 * @return array action filters
	 */
	public function filters() {
		return array('accessControl', // perform access control for CRUD operations
		);
	}

	public function actionIndex() {
		if (!isset(Yii::app() -> user -> customerLogin)) {
			$model = new CustomerLoginForm;
			// jika ajax maka divalidasi dengan ajax
			if (isset($_POST['ajax']) && $_POST['ajax'] === 'login-form') {
				/*tampilkan hasil validasi form*/
				echo CActiveForm::validate($model);
				/*end/exit/die*/
				Yii::app() -> end();
			}

			// ambil data yang diinput oleh user
			if (isset($_POST['CustomerLoginForm'])) {
				$model -> attributes = $_POST['CustomerLoginForm'];
				/*validaasi data yang diinput oleh user dan
				 *jika valid maka ...
				 */
				if ($model -> validate() && $model -> login()) {
					/*redirect ke halaman yang diinginkan
					 **/
					$this -> redirect(array('/'));
				}
			}
			$this -> render("login", array('model' => $model));
		} else {
			$this -> render("index");
		}
	}


	

	public function actionOrders($id = '') {
		IsAuth::Customer();
		/*untuk konfirmasi pembayaran*/
		if(isset($_GET['confirm'])){
			/*panggil model Confirmpayment*/
			$model = new Confirmpayment;
			/*jika data Confirmpayment dikirim dengan method POST*/
			if(isset($_POST['Confirmpayment'])){
				/*set value field*/	
				$order_code = $_POST['Confirmpayment']['nomerPemesanan'];
				$model->attributes = $_POST['Confirmpayment'];
				$model->order_code = $_POST['Confirmpayment']['nomerPemesanan'];
				$model->text_detail .= $_POST['Confirmpayment']['bankAsal'].'#';
				$model->text_detail .= $_POST['Confirmpayment']['pemilikRekAsal'].'#';
				$model->text_detail .= $_POST['Confirmpayment']['bankTujuan'].'#';
				$model->text_detail .=$_POST['Confirmpayment']['nominalTransfer'];
				/*jika data confirmpayment disimpan*/
				if($model->save()){
					/*find data order by attributes berdasarkan order code*/	
					$modelOrder = Order::model()->findByAttributes(array('order_code'=>$order_code));
					/*set field payment_status menjadi 1 
					 *yg artinya telah pembayaran telah dikonfirmasi*/
					$modelOrder->payment_status =1;
					/*simpan perubahan*/
					$modelOrder->save();
					/*setFlash untuk informasi sukses konfirmasi pesanan*/
					Yii::app()->user->setFlash('success', "Pesanan anda dengan nomor pemesanan #".$order_code." telah berhasil dikonfirmasi!"); 
					/*direct ke halaman orders*/
					$this->redirect(array('orders'));
					return;
				}
			}
			/*render ke file account/confirmasi_payment*/
			$this->render('confirm_payment',array('model'=>$model));
			return;
		}
		
		/*untuk halaman list data pesanan*/
		if (empty($id)) {
			/*panggil model Order dan function search*/ 
			$model = new Order('search');
			// hapus default values pada attributes
			$model -> unsetAttributes();
			$model -> customer_id = Yii::app() -> user -> customerId;
			/*jika data order dikirim view get*/
			if (isset($_GET['Order'])){
				/*set attributes untuk pencarian*/
				$model -> attributes = $_GET['Order'];
			}
			/*render ke file account/list_orders*/
			$this -> render('list_orders', array('model' => $model, ));
			return;
		}
		
		/*untuk detail order*/
		if (!empty($id)) {
			/*join query untuk mendapatkan detail order*/
			$dataOrderDetail = Yii::app()->db->createCommand()
				->select('orders.*,orderdetail.*,product.*')
				->from('orders')
				->join('orderdetail','orderdetail.order_id = orders.id')
				->join('product','product.id = orderdetail.product_id')
				->where('orders.id=:id_order',array(':id_order'=>$id))
				->queryAll();
			/*join query untuk mendapatkan data order 
			 *dan customer/pelanggan*/
			$dataOrder = Yii::app()->db->createCommand()
				->select('orders.*,customer.customer_name')
				->from('orders')
				->join('customer','orders.customer_id = customer.customer_id')
				->where('orders.id=:id_order',array(':id_order'=>$id))
				->queryRow();
			/*render ke file account/detail_order*/	 
			$this->render('detail_order',array(
					'dataOrder'=>$dataOrder,
					'orderDetail'=>$dataOrderDetail,
					'subtotal'=>'',
					'grandtotal'=>'',
				)
			);
			return;
		}
	}
	
	
	/*untuk address book pelanggan*/
	public function actionAddressbook() {
		/*cek user login*/	
		IsAuth::Customer();
		/*jika add data address book*/
		if (isset($_GET['add'])) {
			$model = new Address;
			/*jika post addressbook*/
			if (isset($_POST['Address'])) {
				/*set attributes address book*/
				$model -> attributes = $_POST['Address'];
				/*ambil customer id*/
				$model -> customer_id = Yii::app() -> user -> customerId;
				/*ambil address nama*/
				$addressName = $_POST['Address']['name'];
				/*jika berhasil menyimpan data*/
				if ($model -> save()) {
					/*buat setflash*/
					Yii::app() -> user -> setFlash('success', 'Address book baru dengan nama <b>' . $addressName . '</b> berhasil ditambahkan');
					/*direct ke halaman addressbook awal*/
					$this -> redirect(array('account/addressbook'));
				}
			}
			/*render ke view form add addressbook dengan nama(add_addressbook.php)*/
			$this -> render('add_addressbook', array('model' => $model, ));
			return;
		}
		/*jika edit address book*/
		if (isset($_GET['edit'])) {
			/*ambil data addressbook berdasarkan pk*/
			$model = Address::model() -> findByPk($_GET['edit']);
			/*jika post Address*/
			if (isset($_POST['Address'])) {
				/*ambil nilai attributes nya*/
				$model -> attributes = $_POST['Address'];
				/*ambil customer id*/
				$model -> customer_id = Yii::app() -> user -> customerId;
				/*ambil address name*/
				$addressName = $_POST['Address']['name'];
				/*jika berhasil menyimpan data*/
				if ($model -> save()) {
					/*buat Setflash*/
					Yii::app() -> user -> setFlash('success', 'Address book dengan nama <b>' . $addressName . '</b>  berhasil dirubah');
					/*direct ke halaman address book awal*/
					$this -> redirect(array('account/addressbook'));
				}
			}
			/*render ke view form edit address book dengan nama(add_addressbook.php)*/
			$this -> render('add_addressbook', array('model' => $model, ));
			return;
		}
		
		/*untuk menampilkan list data address book*/
		$model = Address::model() -> findAll('customer_id=:customer_id', array(':customer_id' => Yii::app() -> user -> customerId));
		/*render ke view addressbook*/
		$this -> render('addressbook', array('model' => $model, ));
	}

	/**
	 * Log out, dan akan didirect ke halaman homepage.
	 */
	public function actionLogout() {
		/*logout user*/
		Yii::app() -> user -> clearStates();
		/*direct ke halaman yang diinginkan*/
		$this -> redirect(array('/'));
	}

	public function actionRegister() {
		$model = new Customer;
		if (isset($_POST['Customer'])) {
			$model -> attributes = $_POST['Customer'];
			if($model -> save()){
				$this->redirect(array('account/'));
			}
		}
		$this -> render('register', array("model" => $model));
	}

	public function actionChangepassword() {
		/*untuk cek apakah user telah login atau belum*/
		IsAuth::Customer();
		/*findbyPK data user yang login*/
		$model = CustomerChangePassword::model() -> findByPk(Yii::app() -> user -> customerId);
		/*jika POST maka
		 *ubahpassword*/
		if (isset($_POST['CustomerChangePassword'])) {
			$model -> setAttributes($_POST['CustomerChangePassword']);
			$model -> password = $_POST['CustomerChangePassword']['newPassword'];
			/*jika changepassword maka direct ke halaman success*/
			if ($model -> save()) {
				$this -> redirect(array('changepasswordsuccess'));
			}
		}
		/*render ke view ubah password*/
		$this -> render('changepassword', array('model' => $model));
	}

	public function actionChangepasswordsuccess() {
		/*untuk cek apakah user telah login atau belum*/
		IsAuth::Customer();
		/*untuk setflash berhasil ubah password*/
		Yii::app() -> user -> setFlash('success', 'Password anda berhasil dirubah dengan passwod yang baru');
		/*render ke file view*/
		$this -> render('changePasswordSuccess');
	}

	public function actionInfo() {
		IsAuth::Customer();
		$this -> render('info');
	}


	/**
	 * Manages all models.
	 */
	public function actionAdmin() {
		IsAuth::Admin();
		$model = new Customer('search');
		$model -> unsetAttributes();
		// clear any default values
		if (isset($_GET['Customer']))
			$model -> attributes = $_GET['Customer'];

		$this -> render('admin', array('model' => $model, ));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer the ID of the model to be loaded
	 */
	public function loadModel($id) {
		$model = Customer::model() -> findByPk($id);
		if ($model === null)
			throw new CHttpException(404, 'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param CModel the model to be validated
	 */
	protected function performAjaxValidation($model) {
		if (isset($_POST['ajax']) && $_POST['ajax'] === 'customer-form') {
			echo CActiveForm::validate($model);
			Yii::app() -> end();
		}
	}

}

protected/controllers/AdminController.php
<?php

class AdminController extends Controller {

	public $layout = "testing";

	/*action Index admin*/
	public function actionIndex() {
		if(isset(Yii::app()->user->adminLogin)==TRUE){
			$this->redirect(array('product/admin'));
		}
		/*panggil model AdminLoginForm
		 *dan di tampung oleh $model*/
		$model = new AdminLoginForm;

		// jika ajax maka divalidasi dengan ajax
		if (isset($_POST['ajax']) && $_POST['ajax'] === 'login-form') {
			/*tampilkan hasil validasi form*/
			echo CActiveForm::validate($model);
			/*end/exit/die*/
			Yii::app() -> end();
		}

		// ambil data yang diinput oleh user
		if (isset($_POST['AdminLoginForm'])) {
			$model -> attributes = $_POST['AdminLoginForm'];
			/*validaasi data yang diinput oleh user dan
			 * jika valid maka ...
			 */
			if ($model -> validate() && $model -> login()) {
				/*redirect ke halaman yang diinginkan
				 *(dalam hal ini kita direct ke halaman product/admin)
				 **/
				$this -> redirect(array('product/admin'));
			}
		}
		// tampilkan login form
		$this -> render('index', array('model' => $model));
	}

	/**
	 * Log out, dan akan didirect ke halaman homepage.
	 */
	public function actionLogout() {
		/*logout user*/
		Yii::app() -> user -> logout();
		/*direct ke halaman yang diinginkan*/
		$this -> redirect(array('/admin'));
	}

}
?>

protected/controllers/CategoryController.php
<?php

class CategoryController extends Controller{
	 
	public $layout='admin_page';


	public function actionView($id){
		IsAuth::Admin();
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

 	/*create kategori*/
	public function actionCreate(){
		IsAuth::Admin();
		/*panggil model Category*/	
		$model=new Category;
		/*jika data kategori dikirim*/
		if(isset($_POST['Category'])){
			/*set attributes*/	
			$model->attributes=$_POST['Category'];
			/*simpan data kategori*/
			if($model->save()){
				/*direct ke actionView*/
				$this->redirect(array('view','id'=>$model->id));
			}
				
		}
		/*menampilkan form create*/
		$this->render('create',array(
			'model'=>$model,
		));
	}

	/*update category*/
	public function actionUpdate($id){
		IsAuth::Admin();
		/*find data by pk*/	
		$model=$this->loadModel($id);
		/*jika data dikirim*/
		if(isset($_POST['Category'])){
			/*set attributes*/	
			$model->attributes=$_POST['Category'];
			/*simpan perubahan*/
			if($model->save()){
				/*direct ke function actionView*/	
				$this->redirect(array('view','id'=>$model->id));
			}
		}
		/*menampilkan form update*/
		$this->render('update',array(
			'model'=>$model,
		));
	}

	/*untuk delete category*/
	public function actionDelete($id){
		IsAuth::Admin();
		if(Yii::app()->request->isPostRequest){
			$this->loadModel($id)->delete();
			if(!isset($_GET['ajax'])){
				$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
			}
		}else{
			throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
		}
	}

	 

	/*untuk list data category*/
	public function actionAdmin(){
		IsAuth::Admin();
		/*panggil mpdel category->search*/	
		$model=new Category('search');
		$model->unsetAttributes();  // clear any default values
		/*jika data kategory dikirim*/
		if(isset($_GET['Category'])){
			/*maka set attributes/criteria untuk pencarian*/
			$model->attributes=$_GET['Category'];
		}
		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/*untuk find data by pk*/
	public function loadModel($id){
		$model=Category::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/*melakukan ajax validation*/
	protected function performAjaxValidation($model){
		if(isset($_POST['ajax']) && $_POST['ajax']==='category-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}
?>

protected/views/layouts/admin_page.php
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<!--
Design by Free CSS Templates
http://www.freecsstemplates.org
Released for free under a Creative Commons Attribution 2.5 License

Name       : The Fences 
Description: A two-column, fixed-width design for 1024x768 screen resolutions.
Version    : 1.0
Released   : 20100308
-->
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<title>*** Admin Page ***</title>
<meta name="keywords" content="" />
<meta name="description" content="" />
<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/form.css" />
<link href="<?php echo Yii::app()->request->baseUrl;?>/assets/admin/style.css" rel="stylesheet" type="text/css" media="screen" />
</head>
<body>
	<div id="logo">
		<h1><a href="#">ADMIN TOKO ONLINE YIISHOP</a></h1>
	</div>
	 
	<!-- end #logo -->
	<div id="header">
		<div id="menu" style="float: right">
			<ul style="float: right">
			<?php if(isset(Yii::app()->user->username)){?>
				<li><a href="<?php echo $this->createUrl("admin/logout");?>">LOG OUT (<?php echo Yii::app()->user->username;?>)</a></li>
			<?php } ?>
			</ul>	
		</div> 
	</div>
	<!-- end #header -->
	<!-- end #header-wrapper -->
	<div id="main-content">
		<div id="content">
		  <div class="content-data">
					<!--content here-->
					<?php echo $content;?>
					<!--/content-->
		  </div>
		</div>
		<!-- end #content -->
		
		<!--sidebar-->
		<div id="sidebar">
			<ul>
				<li>
					<h2>MENU</h2>
					<ul>
						<li><a href="<?php echo $this->createUrl('product/admin');?>">Produk</a></li>
						<li><a href="<?php echo $this->createUrl('category/admin');?>">Kategory</a></li>
						<li><a href="<?php echo $this->createUrl('orders/admin');?>">Orders</a></li>
					</ul>
					<?php if(isset(Yii::app()->user->rule) =='root'){?>
					<h2>Administration</h2>
					<ul>
						<li><a href="<?php echo $this->createUrl('manageadmin/admin');?>">Data Admin</a></li>
						 
					</ul>
					<?php } ?>
				</li>
			</ul>
		</div>
		<!--/sidebar-->
		<div style="clear: both;">&nbsp;</div>
	</div>
	<!-- end #page -->
	
	<!--footer-->
	<div id="footer">
		<p>Copyright (c) <?php echo date("Y");?> yiishop.com. All rights reserved. Design by <a href="http://www.freecsstemplates.org/">Free CSS Templates</a>.</p>
	</div>
	<!--/footer -->
</body>
</html>

protected/views/layouts/column1.php
<?php $this->beginContent('//layouts/main'); ?>
<div id="content">
	<?php echo $content; ?>
</div><!-- content -->
<?php $this->endContent(); ?>

protected/views/layouts/column2.php
<?php $this->beginContent('//layouts/main'); ?>
<div class="span-19">
	<div id="content">
		<?php echo $content; ?>
	</div><!-- content -->
</div>
<div class="span-5 last">
	<div id="sidebar">
	<?php
		$this->beginWidget('zii.widgets.CPortlet', array(
			'title'=>'Operations',
		));
		$this->widget('zii.widgets.CMenu', array(
			'items'=>$this->menu,
			'htmlOptions'=>array('class'=>'operations'),
		));
		$this->endWidget();
	?>
	</div><!-- sidebar -->
</div>
<?php $this->endContent(); ?>

protected/views/layouts/main.php
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="language" content="en" />

	<!-- blueprint CSS framework -->
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/screen.css" media="screen, projection" />
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/print.css" media="print" />
	<!--[if lt IE 8]>
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/ie.css" media="screen, projection" />
	<![endif]-->

	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/main.css" />
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/form.css" />

	<title><?php echo CHtml::encode($this->pageTitle); ?></title>
</head>

<body>

<div class="container" id="page">

	<div id="header">
		<div id="logo"><?php echo CHtml::encode(Yii::app()->name); ?></div>
	</div><!-- header -->

	<div id="mainmenu">
		<?php $this->widget('zii.widgets.CMenu',array(
			'items'=>array(
				array('label'=>'Home', 'url'=>array('/site/index')),
				array('label'=>'About', 'url'=>array('/site/page', 'view'=>'about')),
				array('label'=>'Contact', 'url'=>array('/site/contact')),
				array('label'=>'Login', 'url'=>array('/site/login'), 'visible'=>Yii::app()->user->isGuest),
				array('label'=>'Logout ('.Yii::app()->user->name.')', 'url'=>array('/site/logout'), 'visible'=>!Yii::app()->user->isGuest)
			),
		)); ?>
	</div><!-- mainmenu -->
	<?php if(isset($this->breadcrumbs)):?>
		<?php $this->widget('zii.widgets.CBreadcrumbs', array(
			'links'=>$this->breadcrumbs,
		)); ?><!-- breadcrumbs -->
	<?php endif?>

	<?php echo $content; ?>

	<div class="clear"></div>

	<div id="footer">
		Copyright &copy; <?php echo date('Y'); ?> by My Company.<br/>
		All Rights Reserved.<br/>
		<?php echo Yii::powered(); ?>
	</div><!-- footer -->

</div><!-- page -->

</body>
</html>

protected/views/layouts/store.php
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<title>Online DVD &amp; Toys store</title>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<link href="<?php echo Yii::app() -> request -> baseUrl; ?>/css/style.css" rel="stylesheet" type="text/css" />
		<link rel="stylesheet" type="text/css" href="<?php echo Yii::app() -> request -> baseUrl; ?>/css/form.css" />
		<style type="text/css">
			.last{
				display: inline !important;
			}
			.first{
				display: inline !important;
			}
			 
		</style>
	</head>
	<body>
		<div id="wrapper">
			<div id="inner">
				<div id="header">
					<h1><img src="<?php echo Yii::app() -> request -> baseUrl; ?>/images/head2.jpg" width="100%" height="63" alt="Online Movie Store" /></h1>	
					<div style="position: absolute;top:20px;right:20px;color:#ffffff;">
						<?php
							if(isset(Yii::app()->user->customerName)){
								echo 'Hello : '.Yii::app()->user->customerName;
						}
						?>	
					</div>
					<div id="nav" style="left: 725px; width: 248px;text-align:right;">
						<a href="<?php echo $this->createUrl('/account');?>">my account</a> | 
						<?php if(isset(Yii::app()->user->customerLogin)){
							echo CHtml::link('Logout',array('account/logout')).' | ';
						} ?>
						<!--<a href="">logout</a> | -->
						<a href="<?php echo $this->createUrl('/cart');?>">view cart</a> | 
						<a href="#">how to buy</a>
					</div>
					<!-- / nav -->
					<a href="#"><img src="<?php echo Yii::app() -> request -> baseUrl; ?>/images/ck_header.jpg" width="100%" height="145" alt="Online Movie Store" /></a>

				</div>
				<!-- / header -->
				<dl id="browse">
					<dt>
						Full Category Lists
					</dt>
					<?php
					/*ambil semua data kategori*/
					$model=Category::model()->findAll();
					/*foreach data kategori*/
					foreach ($model as $data):
					?>
					<dd>
						<?php 
							/*buat link produk berdasarkan kategori*/
							echo CHtml::link(
								/*untuk label link*/
								CHtml::encode($data -> category_name), 
								/*untuk url link*/
								array(
								   'product/category', 
								   'id' => $data -> id, 
								   'c' => $data -> category_name
								)); ?>
					</dd>
					<?php endforeach; ?>
					<dt>
						Search Your Favourite Movie
					</dt>
					<dd class="searchform">
						<form action="<?php echo $this->createUrl('product/search');?>" method="post">
							<div>
								<select name="Search[category]">
									<option value="all-categories">All Categories</option>
									<?php
									$Categories = Category::model()->findAll();
									foreach($Categories as $category):
									?>
									<option value="<?php echo $category->id;?>"><?php echo $category->category_name;?></option>
									<?php endforeach;?>
									 
								</select>
							</div>
							<div>
								<input name="Search[keyword]" type="text" placeholder="DVD TITLE" class="text" />
							</div>
							<div class="softright">
								<input type="image" src="<?php echo Yii::app() -> request -> baseUrl; ?>/images/btn_search.gif" />
							</div>
						</form>
					</dd>
				</dl>
				<div id="body">
					<!-- breadcrumbs-->
					<div style="margin-left: 5px;">
						<!--jika $breadcrumbs tersedia maka-->
						<?php if(isset($this->breadcrumbs)):?>
						<!--tampilkan breadcrumbs-->
						<?php $this -> widget('zii.widgets.CBreadcrumbs', array('links' => $this -> breadcrumbs, )); ?>
						<!--end if-->
						<?php endif ?>
					</div>
					<!-- /breadcrumbs -->

					<div class="inner">
						<!--content here-->
						<?php echo $content;?>
						<!--/content-->
						
						<!-- / inner -->
					</div>
				</div>
				<div style=" border:1px solid #CCC;background:white; margin-top:2px;   width:250px; float:right; margin-left:3px;">

					<div style="border: solid 3px #FFFFFF;">

						Lorem ipsum dolor sit amet, consectetur adipisic ing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
						Lorem ipsum dolor sit amet, consectetur adipisic ing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat

					</div>

				</div>
				<div style=" clear:right;border:1px solid #CCC;background:white; margin-top:2px;   width:250px; float:right; margin-left:3px;">
					<div style="border: solid 3px #FFFFFF; ">
						Lorem ipsum dolor sit amet, consectetur adipisic ing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
						Lorem ipsum dolor sit amet, consectetur adipisic ing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat
					</div>

				</div>
				<br>
				<div style="clear:right;   margin-top:2px;   width:250px; float:right; margin-left:3px;">
					&nbsp;
				</div>
				<!-- / body -->
				<div class="clear"></div>
				<div id="footer" style="text-align: center;">
					<div class="fleft">
						<p>
							Copyright &copy; <?php echo date("Y"); ?>. yiishop.com
						</p>
					</div>
					<div class="fright">
						<p>
							More <a href="http://www.websitetemplatesonline.com" title="WTO - website templates and Flash templates">Free Web Templates</a> at WTO. All <a href="http://www.magentothemesworld.com" title="Best Magento Templates">premium Magento themes</a> at magentothemesworld.com!
						</p>
					</div><div class="fclear"></div>
				</div>
				<!-- / footer -->
			</div>
			<!-- / inner -->
		</div>
		<!-- / wrapper -->
	</body>
</html>

protected/views/layouts/testing.php
<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/form.css" />
<?php echo $content;?>