protected/models/Category.php
<?php
class Category extends CActiveRecord {

	public static function model($className = __CLASS__) {
		return parent::model($className);
	}
	/*tentukan tabel yang akan digunakan (
	 *model ini menggunakan tabel category)*/
	public function tableName() {
		return 'category';
	}
	
	/*set masing-masing rule pada tiap field 
	 *yang ada pada tabel category*/
	public function rules() {
		return array( 
		 	array('category_name', 'required'), 
			array('category_name', 'length', 'max' => 555), 
			array('id, category_name', 'safe', 'on' => 'search'), 
		);
	}
	
	/*set label 
	 *untuk masing-masing attribute atau field*/
	public function attributeLabels() {
		return array(
			'id' => 'ID', 
			'category_name' => 'Category Name', 
		);
	}

	/*untuk search data category*/
	public function search() {
		$criteria = new CDbCriteria;
		$criteria -> compare('id', $this -> id);
		$criteria -> compare('category_name', $this -> category_name, true);
		return new CActiveDataProvider($this, array('criteria' => $criteria, ));
	}
}
?>

protected/controllers/CategoryController.php
<?php

class CategoryController extends Controller{
	 
	public $layout='admin_page';


	public function actionView($id){
		IsAuth::Admin();
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

 	/*create kategori*/
	public function actionCreate(){
		IsAuth::Admin();
		/*panggil model Category*/	
		$model=new Category;
		/*jika data kategori dikirim*/
		if(isset($_POST['Category'])){
			/*set attributes*/	
			$model->attributes=$_POST['Category'];
			/*simpan data kategori*/
			if($model->save()){
				/*direct ke actionView*/
				$this->redirect(array('view','id'=>$model->id));
			}
				
		}
		/*menampilkan form create*/
		$this->render('create',array(
			'model'=>$model,
		));
	}

	/*update category*/
	public function actionUpdate($id){
		IsAuth::Admin();
		/*find data by pk*/	
		$model=$this->loadModel($id);
		/*jika data dikirim*/
		if(isset($_POST['Category'])){
			/*set attributes*/	
			$model->attributes=$_POST['Category'];
			/*simpan perubahan*/
			if($model->save()){
				/*direct ke function actionView*/	
				$this->redirect(array('view','id'=>$model->id));
			}
		}
		/*menampilkan form update*/
		$this->render('update',array(
			'model'=>$model,
		));
	}

	/*untuk delete category*/
	public function actionDelete($id){
		IsAuth::Admin();
		if(Yii::app()->request->isPostRequest){
			$this->loadModel($id)->delete();
			if(!isset($_GET['ajax'])){
				$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
			}
		}else{
			throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
		}
	}

	 

	/*untuk list data category*/
	public function actionAdmin(){
		IsAuth::Admin();
		/*panggil mpdel category->search*/	
		$model=new Category('search');
		$model->unsetAttributes();  // clear any default values
		/*jika data kategory dikirim*/
		if(isset($_GET['Category'])){
			/*maka set attributes/criteria untuk pencarian*/
			$model->attributes=$_GET['Category'];
		}
		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/*untuk find data by pk*/
	public function loadModel($id){
		$model=Category::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/*melakukan ajax validation*/
	protected function performAjaxValidation($model){
		if(isset($_POST['ajax']) && $_POST['ajax']==='category-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}
?>

protected/views/category/_form.php
<div class="form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'category-form',
	'enableAjaxValidation'=>false,
)); ?>

	<p class="note">Fields with <span class="required">*</span> are required.</p>

	<?php echo $form->errorSummary($model); ?>

	<div class="row">
		<?php echo $form->labelEx($model,'category_name'); ?>
		<?php echo $form->textField($model,'category_name',array('size'=>60,'maxlength'=>555)); ?>
		<?php echo $form->error($model,'category_name'); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton($model->isNewRecord ? 'Create' : 'Save'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- form -->

protected/views/category/_search.php
<div class="wide form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<div class="row">
		<?php echo $form->label($model,'id'); ?>
		<?php echo $form->textField($model,'id'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'category_name'); ?>
		<?php echo $form->textField($model,'category_name',array('size'=>60,'maxlength'=>555)); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton('Search'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->

protected/views/category/_view.php
<div class="view">

	<b><?php echo CHtml::encode($data->getAttributeLabel('id')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->id), array('view', 'id'=>$data->id)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('category_name')); ?>:</b>
	<?php echo CHtml::encode($data->category_name); ?>
	<br />


</div>

protected/views/category/admin.php
<h3>Data Categories</h3>

<div>
	<!--membuat link untuk add category-->
	<?php echo CHtml::link('Add Category',array('category/create'));?>
</div>

<style type="text/css">
    /*untuk menampilkan link last pada paging*/
	.last{
		display: inline !important;
	}
	/*untuk menampilkan link first pada paging*/
	.first{
		display: inline !important;
	}
</style>

<?php $this->widget('zii.widgets.grid.CGridView', array(
	'id'=>'category-grid',
	/*untuk search*/
	'dataProvider'=>$model->search(),
	/*membuat filter*/
	'filter'=>$model,
	/*menghilangkan summary text*/
	'summaryText'=>'',
	/*untuk paging*/
	'pager'=>array(
		/*hilangkan header paging*/
        'header'=> '',
        /*untuk label first page*/
        'firstPageLabel'=>'| <',
        /*untuk label last page*/
        'lastPageLabel'=>'> |',
        /*untuk label next page*/
        'nextPageLabel'=>'>',
        /*untuk label prev page*/
        'prevPageLabel'=>'<',
    ),
	'columns'=>array(
		/*menampilkan id kategori*/
		'id',
		/*menampilkan nama kategori*/
		'category_name',
		array(
			'class'=>'CButtonColumn',
			/*template button (update dan delete)*/
			'template'=>'{update}&nbsp;&nbsp;{delete}'
		),
	),
)); ?>

protected/views/category/create.php
<h3>Create Category</h3>
<!--renderPartial _form.php dengan memparsing $model-->
<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/category/index.php
<?php
$this->breadcrumbs=array(
	'Categories',
);

$this->menu=array(
	array('label'=>'Create Category', 'url'=>array('create')),
	array('label'=>'Manage Category', 'url'=>array('admin')),
);
?>

<h3>Categories</h3>

<?php $this->widget('zii.widgets.CListView', array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_view',
)); ?>

protected/views/category/update.php
<h3>Update Category #<?php echo $model->id; ?></h3>

<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/category/view.php
<h3>View Category #<?php echo $model->id; ?></h3>
<!--gunakan zii widgets CDetailView untuk menampilkan detail category-->
<?php $this->widget('zii.widgets.CDetailView', array(
	'data'=>$model,
	'attributes'=>array(
		'id',
		'category_name',
	),
)); ?>